name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        project_id: arcane-shape-449219-v0  # Replace with your Google Cloud Project ID
        credentials: FQHGX2Mi-tP_rtLGDHFBQ5OAKc3vVQ0175  # Use the service account key stored in GitHub Secrets

    - name: Configure Docker
      run: |
        gcloud auth configure-docker

    - name: Build Docker image
      run: |
        gcloud builds submit --tag gcr.io/arcane-shape-449219-v0/gcp_first .

    - name: Deploy to Google Cloud Run
      run: |
        gcloud run deploy gcp_first \
          --image gcr.io/arcane-shape-449219-v0/gcp_first \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated
